// 게시물 인터페이스 정의
export interface BoardPost {
  postId: number;
  nickname: number;
  category: string;
  title: string;
  content: string;
  createdAt: string;
  likes: number;
  likedByUser: boolean;
  images?: string[]; // 이미지 배열 추가
}

// 게시물 데이터
export const posts: BoardPost[] = [
  // ITNews 카테고리
  {
    postId: 1,
    nickname: 1,
    category: 'ITNEWS',
    title: 'IT 소식 제목 1',
    content: 'IT 소식 내용 1',
    createdAt: '2024-06-03T14:23:04',
    likes: 10,
    likedByUser: false,
    images: ['https://via.placeholder.com/300.png?text=Image1', 'https://via.placeholder.com/300.png?text=Image2'],
  },
  {
    postId: 2,
    nickname: 2,
    category: 'ITNEWS',
    title: 'IT 소식 제목 2',
    content: 'IT 소식 내용 2',
    createdAt: '2024-06-03T14:24:05',
    likes: 20,
    likedByUser: false,
    images: [],
  },
  {
    postId: 3,
    nickname: 3,
    category: 'ITNEWS',
    title: 'IT 소식 제목 3',
    content: 'IT 소식 내용 3',
    createdAt: '2024-06-03T14:25:06',
    likes: 5,
    likedByUser: false,
    images: ['https://via.placeholder.com/300.png?text=Image3'],
  },
  {
    postId: 4,
    nickname: 4,
    category: 'ITNEWS',
    title: 'IT 소식 제목 4',
    content: 'IT 소식 내용 4',
    createdAt: '2024-06-03T14:26:07',
    likes: 15,
    likedByUser: false,
    images: [
      'https://via.placeholder.com/300.png?text=Image4',
      'https://via.placeholder.com/300.png?text=Image5',
      'https://via.placeholder.com/300.png?text=Image6',
    ],
  },
  {
    postId: 5,
    nickname: 5,
    category: 'ITNEWS',
    title: 'IT 소식 제목 5',
    content: 'IT 소식 내용 5',
    createdAt: '2024-06-03T14:27:08',
    likes: 8,
    likedByUser: false,
    images: [
      'https://via.placeholder.com/300.png?text=Image7',
      'https://via.placeholder.com/300.png?text=Image8',
      'https://via.placeholder.com/300.png?text=Image9',
      'https://via.placeholder.com/300.png?text=Image10',
      'https://via.placeholder.com/300.png?text=Image11',
    ],
  },

  // Daily 카테고리
  {
    postId: 6,
    nickname: 1,
    category: 'DAILY',
    title: '잡담 제목 1',
    content: '잡담 내용 1',
    createdAt: '2024-06-03T14:33:14',
    likes: 10,
    likedByUser: false,
    images: ['https://via.placeholder.com/300.png?text=Image12', 'https://via.placeholder.com/300.png?text=Image13'],
  },
  {
    postId: 7,
    nickname: 2,
    category: 'DAILY',
    title: '잡담 제목 2',
    content: '잡담 내용 2',
    createdAt: '2024-06-03T14:34:15',
    likes: 20,
    likedByUser: false,
    images: [],
  },
  {
    postId: 8,
    nickname: 3,
    category: 'DAILY',
    title: '잡담 제목 3',
    content: '잡담 내용 3',
    createdAt: '2024-06-03T14:35:16',
    likes: 5,
    likedByUser: false,
    images: ['https://via.placeholder.com/300.png?text=Image14'],
  },
  {
    postId: 9,
    nickname: 4,
    category: 'DAILY',
    title: '잡담 제목 4',
    content: '잡담 내용 4',
    createdAt: '2024-06-03T14:36:17',
    likes: 15,
    likedByUser: false,
    images: ['https://via.placeholder.com/300.png?text=Image15', 'https://via.placeholder.com/300.png?text=Image16'],
  },
  {
    postId: 10,
    nickname: 5,
    category: 'DAILY',
    title: '잡담 제목 5',
    content: '잡담 내용 5',
    createdAt: '2024-06-03T14:37:18',
    likes: 8,
    likedByUser: false,
    images: [],
  },

  // Tech 카테고리
  {
    postId: 11,
    nickname: 1,
    category: 'TECH',
    title: '기술 제목 1',
    content: '기술 내용 1',
    createdAt: '2024-06-03T14:43:24',
    likes: 10,
    likedByUser: false,
    images: ['https://via.placeholder.com/300.png?text=Image17'],
  },
  {
    postId: 12,
    nickname: 2,
    category: 'TECH',
    title: '기술 제목 2',
    content: '기술 내용 2',
    createdAt: '2024-06-03T14:44:25',
    likes: 20,
    likedByUser: false,
    images: [],
  },
  {
    postId: 13,
    nickname: 3,
    category: 'TECH',
    title: '기술 제목 3',
    content: '기술 내용 3',
    createdAt: '2024-06-03T14:45:26',
    likes: 5,
    likedByUser: false,
    images: ['https://via.placeholder.com/300.png?text=Image18', 'https://via.placeholder.com/300.png?text=Image19'],
  },
  {
    postId: 14,
    nickname: 4,
    category: 'TECH',
    title: '기술 제목 4',
    content: '기술 내용 4',
    createdAt: '2024-06-03T14:46:27',
    likes: 15,
    likedByUser: false,
    images: [
      'https://via.placeholder.com/300.png?text=Image20',
      'https://via.placeholder.com/300.png?text=Image21',
      'https://via.placeholder.com/300.png?text=Image22',
    ],
  },
  {
    postId: 15,
    nickname: 5,
    category: 'TECH',
    title: '기술 제목 5',
    content: '기술 내용 5',
    createdAt: '2024-06-03T14:47:28',
    likes: 8,
    likedByUser: false,
    images: ['https://via.placeholder.com/300.png?text=Image23', 'https://via.placeholder.com/300.png?text=Image24'],
  },

  // InternShip 카테고리
  {
    postId: 16,
    nickname: 1,
    category: 'INTERNSHIP',
    title: '인턴십 제목 1',
    content: '인턴십 내용 1',
    createdAt: '2024-06-03T14:53:34',
    likes: 10,
    likedByUser: false,
    images: ['https://via.placeholder.com/300.png?text=Image25'],
  },
  {
    postId: 17,
    nickname: 2,
    category: 'INTERNSHIP',
    title: '인턴십 제목 2',
    content: '인턴십 내용 2',
    createdAt: '2024-06-03T14:54:35',
    likes: 20,
    likedByUser: false,
    images: [],
  },
  {
    postId: 18,
    nickname: 3,
    category: 'INTERNSHIP',
    title: '인턴십 제목 3',
    content: '인턴십 내용 3',
    createdAt: '2024-06-03T14:55:36',
    likes: 5,
    likedByUser: false,
    images: ['https://via.placeholder.com/300.png?text=Image26', 'https://via.placeholder.com/300.png?text=Image27'],
  },
  {
    postId: 19,
    nickname: 4,
    category: 'INTERNSHIP',
    title: '인턴십 제목 4',
    content: '인턴십 내용 4',
    createdAt: '2024-06-03T14:56:37',
    likes: 15,
    likedByUser: false,
    images: [
      'https://via.placeholder.com/300.png?text=Image28',
      'https://via.placeholder.com/300.png?text=Image29',
      'https://via.placeholder.com/300.png?text=Image30',
    ],
  },
  {
    postId: 20,
    nickname: 5,
    category: 'INTERNSHIP',
    title: '인턴십 제목 5',
    content: '인턴십 내용 5',
    createdAt: '2024-06-03T14:57:38',
    likes: 8,
    likedByUser: false,
    images: ['https://via.placeholder.com/300.png?text=Image31', 'https://via.placeholder.com/300.png?text=Image32'],
  },

  // Notice 카테고리
  {
    postId: 21,
    nickname: 1,
    category: 'NOTICE',
    title: '공지사항 제목 1',
    content: '공지사항 내용 1',
    createdAt: '2024-06-03T15:03:44',
    likes: 10,
    likedByUser: false,
    images: ['https://via.placeholder.com/300.png?text=Image33'],
  },
  {
    postId: 22,
    nickname: 2,
    category: 'NOTICE',
    title: '공지사항 제목 2',
    content: '공지사항 내용 2',
    createdAt: '2024-06-03T15:04:45',
    likes: 20,
    likedByUser: false,
    images: [],
  },
  {
    postId: 23,
    nickname: 3,
    category: 'NOTICE',
    title: '공지사항 제목 3',
    content: '공지사항 내용 3',
    createdAt: '2024-06-03T15:05:46',
    likes: 5,
    likedByUser: false,
    images: ['https://via.placeholder.com/300.png?text=Image34', 'https://via.placeholder.com/300.png?text=Image35'],
  },
  {
    postId: 24,
    nickname: 4,
    category: 'NOTICE',
    title: '공지사항 제목 4',
    content: '공지사항 내용 4',
    createdAt: '2024-06-03T15:06:47',
    likes: 15,
    likedByUser: false,
    images: [
      'https://via.placeholder.com/300.png?text=Image36',
      'https://via.placeholder.com/300.png?text=Image37',
      'https://via.placeholder.com/300.png?text=Image38',
    ],
  },
  {
    postId: 25,
    nickname: 5,
    category: 'NOTICE',
    title: '공지사항 제목 5',
    content: '공지사항 내용 5',
    createdAt: '2024-06-03T15:07:48',
    likes: 8,
    likedByUser: false,
    images: ['https://via.placeholder.com/300.png?text=Image39', 'https://via.placeholder.com/300.png?text=Image40'],
  },
];
